import owal from "../assets/owal.png";

const profiles = [
  {
    className: "snap-center",
    cover: "red",
    name: "zayden",
    followers: "8M",
    following: "5M",
    image: owal,
    location: "Mumbai, Maharashtra",
  },
  {
    className: "snap-center",
    cover: "blue",
    name: "lyra",
    followers: "10M",
    following: "7M",
    image: owal,
    location: "Bangalore, Karnataka",
  },
  {
    className: "snap-center",
    cover: "purple",
    name: "kairo",
    followers: "6M",
    following: "9M",
    image: owal,
    location: "Delhi, India",
  },
  {
    className: "snap-center",
    cover: "yellow",
    name: "selene",
    followers: "12.5M",
    following: "11M",
    image: owal,
    location: "Chennai, Tamil Nadu",
  },
  {
    className: "snap-center",
    cover: "green",
    name: "daxton",
    followers: "4M",
    following: "6M",
    image: owal,
    location: "Kolkata, West Bengal",
  },
  {
    className: "snap-center",
    cover: "blue",
    name: "astra",
    followers: "14M",
    following: "13M",
    image: owal,
    location: "Hyderabad, Telangana",
  },
  {
    className: "snap-center",
    cover: "purple",
    name: "maverick",
    followers: "9M",
    following: "10M",
    image: owal,
    location: "Jaipur, Rajasthan",
  },
  {
    className: "snap-center",
    cover: "yellow",
    name: "zephyr",
    followers: "3M",
    following: "4M",
    image: owal,
    location: "Lucknow, Uttar Pradesh",
  },
  {
    className: "snap-center",
    cover: "red",
    name: "sienna",
    followers: "11M",
    following: "14M",
    image: owal,
    location: "Pune, Maharashtra",
  },
  {
    className: "snap-center",
    cover: "green",
    name: "phoenix",
    followers: "7M",
    following: "8M",
    image: owal,
    location: "Bhopal, Madhya Pradesh",
  },
  {
    className: "snap-center",
    cover: "blue",
    name: "nexus",
    followers: "5.5M",
    following: "6.5M",
    image: owal,
    location: "Indore, Madhya Pradesh",
  },
  {
    className: "snap-center",
    cover: "purple",
    name: "nova",
    followers: "8.3M",
    following: "9.2M",
    image: owal,
    location: "Nagpur, Maharashtra",
  },
  {
    className: "snap-center",
    cover: "red",
    name: "riven",
    followers: "13M",
    following: "12.8M",
    image: owal,
    location: "Chandigarh, Punjab",
  },
  {
    className: "snap-center",
    cover: "yellow",
    name: "zenith",
    followers: "2M",
    following: "3M",
    image: owal,
    location: "Ahmedabad, Gujarat",
  },
  {
    className: "snap-center",
    cover: "blue",
    name: "orion",
    followers: "9.7M",
    following: "10.3M",
    image: owal,
    location: "Goa, India",
  },
  {
    className: "snap-center",
    cover: "green",
    name: "lyric",
    followers: "6.9M",
    following: "8.1M",
    image: owal,
    location: "Coimbatore, Tamil Nadu",
  },
  {
    className: "snap-center",
    cover: "purple",
    name: "elara",
    followers: "5M",
    following: "4M",
    image: owal,
    location: "Surat, Gujarat",
  },
  {
    className: "snap-center",
    cover: "red",
    name: "caspian",
    followers: "7.5M",
    following: "9M",
    image: owal,
    location: "Patna, Bihar",
  },
  {
    className: "snap-center",
    cover: "yellow",
    name: "astraea",
    followers: "15M",
    following: "13.5M",
    image: owal,
    location: "Thiruvananthapuram, Kerala",
  },
  {
    className: "snap-center",
    cover: "blue",
    name: "onyx",
    followers: "4.8M",
    following: "5.6M",
    image: owal,
    location: "Shimla, Himachal Pradesh",
  },
];

export default profiles;
